name: Build WPF App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Cho phép anh hai bấm chạy thủ công trên web

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Đã nâng cấp lên v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4 # Đã nâng cấp lên v4
      with:
        dotnet-version: '8.0.x' 

    - name: Build and Publish
      run: |
        cd PhoiLo
        dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:EnableWindowsTargeting=true -o ../publish

    - name: Upload Artifact
      uses: actions/upload-artifact@v4 # Đã nâng cấp lên v4 và sửa lại cho chuẩn
      with:
        name: PhoiLo-App
        path: publish/